// GENERATED FILE — do not edit by hand.
// Built from docs/knowledge/sv/*.md by scripts/build-knowledge-corpus.mjs.
// Regenerate with: pnpm build:knowledge
import type { KnowledgeChunk } from "./retrieval";

export const KNOWLEDGE_CORPUS: KnowledgeChunk[] = [
  {
    id: "arbetsgivaravgifter#0",
    docId: "arbetsgivaravgifter",
    title: "Arbetsgivaravgifter och arbetsgivardeklaration på individnivå",
    heading: "Avgiftsnivåer",
    text: "- Full arbetsgivaravgift är 31,42 procent av underlaget (socialavgiftslagen (2000:980)).\n- Underlaget är kontant bruttolön plus skattepliktiga förmåner.\n- Ålderspensionsavgiften 10,21 procent är en av delavgifterna och ingår i de 31,42 procenten.\n- För anställda som vid årets ingång har fyllt 66 år betalas endast ålderspensionsavgiften 10,21 procent.\n- För anställda födda 1937 eller tidigare betalas inga arbetsgivaravgifter alls.\n- Ersättningar till en person som understiger 1 000 kronor under året är undantagna från arbetsgivaravgifter.",
    source: "Skatteverket — Arbetsgivaravgifter; socialavgiftslagen (2000:980)",
    url: "https://www.skatteverket.se/foretag/arbetsgivare",
    effective: "2026-07-04",
  },
  {
    id: "arbetsgivaravgifter#1",
    docId: "arbetsgivaravgifter",
    title: "Arbetsgivaravgifter och arbetsgivardeklaration på individnivå",
    heading: "Växa-stöd",
    text: "- Växa-stödet ger nedsättning av arbetsgivaravgiften till enbart ålderspensionsavgift 10,21 procent för de första anställda, under vissa villkor om företagsform, anställningens längd och lönetak.\n- Villkoren och taknivåerna fastställs i lag och kan ändras mellan år — kontrollera aktuella villkor hos Skatteverket före tillämpning.",
    source: "Skatteverket — Arbetsgivaravgifter; socialavgiftslagen (2000:980)",
    url: "https://www.skatteverket.se/foretag/arbetsgivare",
    effective: "2026-07-04",
  },
  {
    id: "arbetsgivaravgifter#2",
    docId: "arbetsgivaravgifter",
    title: "Arbetsgivaravgifter och arbetsgivardeklaration på individnivå",
    heading: "Arbetsgivardeklaration (AGI)",
    text: "- Arbetsgivardeklaration lämnas månatligen på individnivå (AGI) — uppgifter per betalningsmottagare i stället för en årlig kontrolluppgift.\n- Deklarationen redovisar bruttolön, skattepliktiga förmåner, avdragen preliminärskatt och arbetsgivaravgifter för varje anställd.\n- Deklaration och betalning: senast den 12:e i månaden efter löneutbetalningsmånaden; i januari och augusti gäller den 17:e.\n- Om tidpunkten infaller på en lördag, söndag eller allmän helgdag gäller närmast följande vardag.\n- Både avgifterna och den avdragna personalskatten betalas till skattekontot senast samma dag.",
    source: "Skatteverket — Arbetsgivaravgifter; socialavgiftslagen (2000:980)",
    url: "https://www.skatteverket.se/foretag/arbetsgivare",
    effective: "2026-07-04",
  },
  {
    id: "arbetsgivaravgifter#3",
    docId: "arbetsgivaravgifter",
    title: "Arbetsgivaravgifter och arbetsgivardeklaration på individnivå",
    heading: "Bokföring",
    text: "- Bruttolönen kostnadsförs i kontogrupp 70–72, till exempel 7010 Löner till kollektivanställda eller 7210 Löner till tjänstemän.\n- Avdragen preliminärskatt bokförs som skuld på 2710 Personalskatt.\n- Arbetsgivaravgifterna kostnadsförs på 7510 Lagstadgade sociala avgifter med motsvarande skuld på 2731 Avräkning lagstadgade sociala avgifter.\n- Skulderna på 2710 och 2731 regleras när betalningen till skattekontot bokförs.",
    source: "Skatteverket — Arbetsgivaravgifter; socialavgiftslagen (2000:980)",
    url: "https://www.skatteverket.se/foretag/arbetsgivare",
    effective: "2026-07-04",
  },
  {
    id: "arsredovisning-ab#0",
    docId: "arsredovisning-ab",
    title: "Årsredovisning för aktiebolag — innehåll och tidsfrister",
    heading: "Skyldighet och innehåll",
    text: "- Alla aktiebolag ska upprätta en årsredovisning och lämna in den till Bolagsverket, oavsett storlek och oavsett om bolaget varit aktivt eller vilande.\n- Årsredovisningen består av förvaltningsberättelse, resultaträkning, balansräkning och noter (årsredovisningslagen (1995:1554)).\n- Större företag ska även upprätta en kassaflödesanalys.\n- Ett fastställelseintyg i original ska bifogas när årsredovisningen ges in till Bolagsverket.\n- Årsredovisningen undertecknas av samtliga styrelseledamöter och av den verkställande direktören.",
    source: "Årsredovisningslagen (1995:1554) 8 kap. 3 §; Bolagsverket — Årsredovisning för aktiebolag",
    url: "https://bolagsverket.se/foretag/aktiebolag/arsredovisningforaktiebolag",
    effective: "2026-07-04",
  },
  {
    id: "arsredovisning-ab#1",
    docId: "arsredovisning-ab",
    title: "Årsredovisning för aktiebolag — innehåll och tidsfrister",
    heading: "Tidsfrister",
    text: "- Årsstämman ska hållas inom sex månader från räkenskapsårets utgång och fastställer där resultat- och balansräkningen (aktiebolagslagen).\n- Årsredovisningen ska ha kommit in till Bolagsverket senast sju månader efter räkenskapsårets slut; fristen följer av att kopian ska ges in inom en månad efter det att stämman fastställde balans- och resultaträkningen (ÅRL 8 kap. 3 §).\n- För bolag med kalenderår som räkenskapsår betyder det senast den 31 juli året därpå.\n- Förseningsavgift för privata aktiebolag: 5 000 kronor vid försening, ytterligare 5 000 kronor efter två månader och ytterligare 10 000 kronor efter fyra månader.\n- Om ingen årsredovisning kommit in inom elva månader från räkenskapsårets utgång kan Bolagsverket besluta att bolaget ska gå i likvidation, och styrelsen kan bli personligt ansvarig.",
    source: "Årsredovisningslagen (1995:1554) 8 kap. 3 §; Bolagsverket — Årsredovisning för aktiebolag",
    url: "https://bolagsverket.se/foretag/aktiebolag/arsredovisningforaktiebolag",
    effective: "2026-07-04",
  },
  {
    id: "arsredovisning-ab#2",
    docId: "arsredovisning-ab",
    title: "Årsredovisning för aktiebolag — innehåll och tidsfrister",
    heading: "Regelverk: K2 och K3",
    text: "- Mindre aktiebolag får upprätta årsredovisningen enligt det förenklade regelverket K2 (BFNAR 2016:10).\n- Övriga upprättar enligt huvudregelverket K3 (BFNAR 2012:1); K3 får alltid väljas frivilligt.\n- Ett företag räknas som större när mer än ett av följande gränsvärden uppfyllts två räkenskapsår i rad: fler än 50 anställda i medeltal, mer än 40 miljoner kronor i balansomslutning, mer än 80 miljoner kronor i nettoomsättning.",
    source: "Årsredovisningslagen (1995:1554) 8 kap. 3 §; Bolagsverket — Årsredovisning för aktiebolag",
    url: "https://bolagsverket.se/foretag/aktiebolag/arsredovisningforaktiebolag",
    effective: "2026-07-04",
  },
  {
    id: "arsredovisning-ab#3",
    docId: "arsredovisning-ab",
    title: "Årsredovisning för aktiebolag — innehåll och tidsfrister",
    heading: "Revisor",
    text: "- Privata aktiebolag kan välja bort revisor om de under vart och ett av de två senaste räkenskapsåren inte uppfyllt mer än ett av följande: fler än 3 anställda i medeltal, mer än 1,5 miljoner kronor i balansomslutning, mer än 3 miljoner kronor i nettoomsättning.\n- Beslutet att inte ha revisor kräver stöd i bolagsordningen.",
    source: "Årsredovisningslagen (1995:1554) 8 kap. 3 §; Bolagsverket — Årsredovisning för aktiebolag",
    url: "https://bolagsverket.se/foretag/aktiebolag/arsredovisningforaktiebolag",
    effective: "2026-07-04",
  },
  {
    id: "arsredovisning-ab#4",
    docId: "arsredovisning-ab",
    title: "Årsredovisning för aktiebolag — innehåll och tidsfrister",
    heading: "Digital inlämning",
    text: "- Årsredovisningen kan lämnas in digitalt (iXBRL) via Bolagsverkets e-tjänst; digital inlämning ger automatisk mottagningskontroll.",
    source: "Årsredovisningslagen (1995:1554) 8 kap. 3 §; Bolagsverket — Årsredovisning för aktiebolag",
    url: "https://bolagsverket.se/foretag/aktiebolag/arsredovisningforaktiebolag",
    effective: "2026-07-04",
  },
  {
    id: "bas-konton-oversikt#0",
    docId: "bas-konton-oversikt",
    title: "BAS-kontoplanen — struktur och vanliga konton",
    heading: "Vad BAS-kontoplanen är",
    text: "- BAS är den svenska standardkontoplanen. Den förvaltas av BAS-intressenternas Förening (BAS-kontogruppen) och uppdateras årligen; aktuell utgåva är Kontoplan BAS 2026.\n- BAS är frivillig att använda men är de facto-standard i svenska bokföringsprogram och ligger till grund för koppling till SRU-koder i inkomstdeklarationen.\n- Kontonumren är fyrsiffriga. Första siffran anger kontoklass och de två första siffrorna anger kontogrupp.\n- Kontoplanen är generell: företag väljer ut de konton som behövs och kan lägga till egna underkonton inom strukturen.",
    source: "BAS-intressenternas Förening — Kontoplan BAS 2026",
    url: "https://www.bas.se/kontoplaner/",
    effective: "2026-01-01",
  },
  {
    id: "bas-konton-oversikt#1",
    docId: "bas-konton-oversikt",
    title: "BAS-kontoplanen — struktur och vanliga konton",
    heading: "Kontoklasserna 1–8",
    text: "- Klass 1: Tillgångar — till exempel 1510 Kundfordringar och 1930 Företagskonto/checkkonto.\n- Klass 2: Eget kapital och skulder — till exempel 2081 Aktiekapital, 2440 Leverantörsskulder och momskontona i grupp 26.\n- Klass 3: Rörelsens inkomster/intäkter — till exempel 3001 Försäljning inom Sverige, 25 % moms.\n- Klass 4: Utgifter/kostnader för varor, material och vissa köpta tjänster — till exempel 4010 Inköp av varor.\n- Klass 5–6: Övriga externa rörelseutgifter/kostnader — lokal, bil, förbrukning, köpta tjänster med mera.\n- Klass 7: Utgifter/kostnader för personal, avskrivningar med mera — till exempel 7010 Löner och 7510 Lagstadgade sociala avgifter.\n- Klass 8: Finansiella och andra inkomster/intäkter och utgifter/kostnader — till exempel 8999 Årets resultat.",
    source: "BAS-intressenternas Förening — Kontoplan BAS 2026",
    url: "https://www.bas.se/kontoplaner/",
    effective: "2026-01-01",
  },
  {
    id: "bas-konton-oversikt#2",
    docId: "bas-konton-oversikt",
    title: "BAS-kontoplanen — struktur och vanliga konton",
    heading: "Vanliga konton i ett mindre företag",
    text: "- 1510 Kundfordringar, 1930 Företagskonto.\n- 2440 Leverantörsskulder, 2710 Personalskatt (avdragen preliminärskatt), 2731 Avräkning lagstadgade sociala avgifter.\n- 2081 Aktiekapital, 2098 Vinst eller förlust från föregående år, 2099 Årets resultat.\n- 3001 Försäljning inom Sverige 25 % moms.\n- 4010 Inköp av varor.\n- 5010 Lokalhyra, 5610 Personbilskostnader.\n- 6071 Representation, avdragsgill, 6072 Representation, ej avdragsgill, 6540 IT-tjänster.\n- 7010 Löner till kollektivanställda, 7510 Lagstadgade sociala avgifter.\n- 8999 Årets resultat (motkonto 2099 vid resultatdisposition).",
    source: "BAS-intressenternas Förening — Kontoplan BAS 2026",
    url: "https://www.bas.se/kontoplaner/",
    effective: "2026-01-01",
  },
  {
    id: "bas-konton-oversikt#3",
    docId: "bas-konton-oversikt",
    title: "BAS-kontoplanen — struktur och vanliga konton",
    heading: "Momskonton i kontogrupp 26",
    text: "- 2610 Utgående moms 25 %.\n- 2620 Utgående moms 12 %.\n- 2630 Utgående moms 6 %.\n- 2640 Ingående moms.\n- 2650 Redovisningskonto för moms — dit utgående och ingående moms bokas om när momsdeklarationen upprättas.\n- Saldot på 2650 motsvarar det belopp som ska betalas till eller fås tillbaka från Skatteverket (ruta 49 i momsdeklarationen).",
    source: "BAS-intressenternas Förening — Kontoplan BAS 2026",
    url: "https://www.bas.se/kontoplaner/",
    effective: "2026-01-01",
  },
  {
    id: "bokforingslagen-verifikationer#0",
    docId: "bokforingslagen-verifikationer",
    title: "Bokföringslagen — verifikationer, löpande bokföring och arkivering",
    heading: "Verifikationskravet",
    text: "- För varje affärshändelse ska det finnas en verifikation (5 kap. 6 § bokföringslagen (1999:1078)).\n- Har företaget tagit emot en uppgift om affärshändelsen (till exempel en faktura eller ett kvitto) ska den uppgiften användas som verifikation.\n- En verifikation ska innehålla (5 kap. 7 §): uppgift om när den har sammanställts, när affärshändelsen har inträffat, vad denna avser, vilket belopp den gäller och vilken motpart den berör, samt i förekommande fall hänvisning till andra handlingar som legat till grund för affärshändelsen.\n- Verifikationer ska ha verifikationsnummer eller andra identifieringstecken så att sambandet mellan verifikation och bokförd post kan fastställas.",
    source: "Bokföringslagen (1999:1078) 5 kap. och 7 kap.",
    url: "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/bokforingslag-19991078_sfs-1999-1078/",
    effective: "2024-07-01",
  },
  {
    id: "bokforingslagen-verifikationer#1",
    docId: "bokforingslagen-verifikationer",
    title: "Bokföringslagen — verifikationer, löpande bokföring och arkivering",
    heading: "Löpande bokföring",
    text: "- Kontanta in- och utbetalningar ska grundbokföras senast påföljande arbetsdag (5 kap. 2 §).\n- Andra affärshändelser ska bokföras så snart det kan ske.\n- Affärshändelserna ska kunna presenteras i registreringsordning (grundbokföring) och i systematisk ordning (huvudbokföring), så att det går att överblicka verksamhetens förlopp, ställning och resultat.",
    source: "Bokföringslagen (1999:1078) 5 kap. och 7 kap.",
    url: "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/bokforingslag-19991078_sfs-1999-1078/",
    effective: "2024-07-01",
  },
  {
    id: "bokforingslagen-verifikationer#2",
    docId: "bokforingslagen-verifikationer",
    title: "Bokföringslagen — verifikationer, löpande bokföring och arkivering",
    heading: "Rättelser",
    text: "- En bokförd post rättas genom en särskild rättelsepost; det ska framgå när rättelsen har skett och vem som har gjort den (5 kap. 5 §).\n- Den ursprungliga posten får inte utplånas eller göras oläslig — bokföringen är tillägg-endast till sin karaktär.\n- Sker rättelsen genom en ny verifikation ska hänvisning finnas mellan den ursprungliga verifikationen och rättelseverifikationen.",
    source: "Bokföringslagen (1999:1078) 5 kap. och 7 kap.",
    url: "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/bokforingslag-19991078_sfs-1999-1078/",
    effective: "2024-07-01",
  },
  {
    id: "bokforingslagen-verifikationer#3",
    docId: "bokforingslagen-verifikationer",
    title: "Bokföringslagen — verifikationer, löpande bokföring och arkivering",
    heading: "Arkivering",
    text: "- Räkenskapsinformation ska bevaras i sju år efter utgången av det kalenderår då räkenskapsåret avslutades (7 kap. 2 §).\n- Sedan den 1 juli 2024 behöver pappersoriginal inte längre sparas efter att räkenskapsinformationen har överförts till digital form — det är den digitala formen som därefter ska bevaras.\n- Räkenskapsinformationen ska förvaras i Sverige, i ordnat skick och på betryggande och överskådligt sätt (7 kap. 2 §), med vissa möjligheter till förvaring utomlands inom EU.",
    source: "Bokföringslagen (1999:1078) 5 kap. och 7 kap.",
    url: "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/bokforingslag-19991078_sfs-1999-1078/",
    effective: "2024-07-01",
  },
  {
    id: "bokforingslagen-verifikationer#4",
    docId: "bokforingslagen-verifikationer",
    title: "Bokföringslagen — verifikationer, löpande bokföring och arkivering",
    heading: "God redovisningssed",
    text: "- Bokföringsskyldigheten ska fullgöras på ett sätt som överensstämmer med god redovisningssed (4 kap. 2 §).\n- Bokföringsnämnden (BFN) ansvarar för utvecklandet av god redovisningssed och ger ut allmänna råd, bland annat K-regelverken.",
    source: "Bokföringslagen (1999:1078) 5 kap. och 7 kap.",
    url: "https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/bokforingslag-19991078_sfs-1999-1078/",
    effective: "2024-07-01",
  },
  {
    id: "f-skatt-preliminarskatt#0",
    docId: "f-skatt-preliminarskatt",
    title: "F-skatt och debiterad preliminärskatt",
    heading: "Vad godkännande för F-skatt innebär",
    text: "- Godkännande för F-skatt (9 kap. skatteförfarandelagen (2011:1244)) innebär att företaget självt ansvarar för att betala sin preliminära skatt och sina socialavgifter.\n- Uppdragsgivare ska inte göra skatteavdrag eller betala arbetsgivaravgifter på ersättning för arbete till den som är godkänd för F-skatt, när godkännandet åberopas i faktura eller avtal.\n- Godkännandet söks hos Skatteverket och kan återkallas bland annat vid brister i redovisning eller betalning av skatter.\n- Fysiska personer som har både anställning och näringsverksamhet kan ha FA-skatt: F-skatt för näringsdelen och A-skatt för anställningen.",
    source: "Skatteverket — F-skatt; skatteförfarandelagen 9 kap.",
    url: "https://www.skatteverket.se/foretag/skatterochavdrag/fskatt",
    effective: "2026-07-04",
  },
  {
    id: "f-skatt-preliminarskatt#1",
    docId: "f-skatt-preliminarskatt",
    title: "F-skatt och debiterad preliminärskatt",
    heading: "Debiterad preliminärskatt — betalning",
    text: "- Skatteverket debiterar preliminärskatt som betalas löpande under beskattningsåret, normalt uppdelad i lika stora månadsbelopp.\n- Förfallodag: den 12:e varje månad, utom i januari och augusti då förfallodagen är den 17:e.\n- Betalningen görs till skattekontot och ska vara bokförd på Skatteverkets konto senast på förfallodagen.\n- Om förfallodagen infaller på en lördag, söndag eller allmän helgdag gäller närmast följande vardag.",
    source: "Skatteverket — F-skatt; skatteförfarandelagen 9 kap.",
    url: "https://www.skatteverket.se/foretag/skatterochavdrag/fskatt",
    effective: "2026-07-04",
  },
  {
    id: "f-skatt-preliminarskatt#2",
    docId: "f-skatt-preliminarskatt",
    title: "F-skatt och debiterad preliminärskatt",
    heading: "Hur preliminärskatten bestäms",
    text: "- Schablonberäkning: preliminärskatten bestäms normalt till 110 procent av den slutliga skatten enligt senaste beslut (105 procent om den slutliga skatten understeg den ursprungligen debiterade preliminärskatten).\n- Om resultatet väntas avvika väsentligt kan företaget lämna en preliminär inkomstdeklaration; Skatteverket beslutar då om ändrad debitering.\n- En preliminär inkomstdeklaration kan lämnas när som helst under året, även flera gånger.",
    source: "Skatteverket — F-skatt; skatteförfarandelagen 9 kap.",
    url: "https://www.skatteverket.se/foretag/skatterochavdrag/fskatt",
    effective: "2026-07-04",
  },
  {
    id: "f-skatt-preliminarskatt#3",
    docId: "f-skatt-preliminarskatt",
    title: "F-skatt och debiterad preliminärskatt",
    heading: "För aktiebolag",
    text: "- Aktiebolag betalar preliminär skatt på bolagets förväntade vinst.\n- Bolagsskatten är 20,6 procent av det skattemässiga resultatet (skattesatsen gäller sedan den 1 januari 2021).\n- Den debiterade preliminärskatten stäms av mot den slutliga skatten efter inkomstdeklarationen; skillnaden regleras via skattekontot.",
    source: "Skatteverket — F-skatt; skatteförfarandelagen 9 kap.",
    url: "https://www.skatteverket.se/foretag/skatterochavdrag/fskatt",
    effective: "2026-07-04",
  },
  {
    id: "f-skatt-preliminarskatt#4",
    docId: "f-skatt-preliminarskatt",
    title: "F-skatt och debiterad preliminärskatt",
    heading: "Skattekontot",
    text: "- Skattekontot samlar preliminärskatt, moms, arbetsgivaravgifter och avdragen personalskatt.\n- Underskott på skattekontot ger kostnadsränta; överskott kan ge låg intäktsränta och kan betalas ut.",
    source: "Skatteverket — F-skatt; skatteförfarandelagen 9 kap.",
    url: "https://www.skatteverket.se/foretag/skatterochavdrag/fskatt",
    effective: "2026-07-04",
  },
  {
    id: "moms-avdrag-grunder#0",
    docId: "moms-avdrag-grunder",
    title: "Momsavdrag — grunderna för ingående moms",
    heading: "Rätten till avdrag",
    text: "- Den som bedriver momspliktig verksamhet får dra av ingående moms på inköp som används i den momspliktiga verksamheten (13 kap. mervärdesskattelagen (2023:200)).\n- Avdraget kräver underlag: en faktura som uppfyller mervärdesskattelagens innehållskrav (17 kap.), bland annat säljarens momsregistreringsnummer, beskattningsunderlag per skattesats och momsbeloppet.\n- En förenklad faktura räcker som underlag om totalbeloppet är högst 4 000 kronor inklusive moms.\n- Ingående moms som avser momsfri verksamhet får inte dras av.\n- Vid blandad verksamhet (både momspliktig och momsfri) fördelas den ingående momsen; avdrag medges för den del som avser den momspliktiga delen, vid behov efter skälig grund.",
    source: "Skatteverket — Avdragsrätt för ingående moms; Mervärdesskattelagen (2023:200)",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-19",
  },
  {
    id: "moms-avdrag-grunder#1",
    docId: "moms-avdrag-grunder",
    title: "Momsavdrag — grunderna för ingående moms",
    heading: "Skattesatserna",
    text: '- 25 procent är normalskattesatsen och gäller de flesta varor och tjänster.\n- 12 procent gäller bland annat restaurang- och cateringtjänster (dock 25 procent på alkohol) samt rumsuthyrning i hotellverksamhet.\n- 6 procent gäller bland annat böcker och tidningar, persontransporter samt entré till kultur- och idrottsevenemang.\n- Livsmedel har tillfälligt sänkt moms från 12 till 6 procent under perioden 1 april 2026–31 december 2027; alkoholhaltiga drycker omfattas inte utan ligger kvar på 25 procent (Skatteverket, "Livsmedelsmomsen sänks till 6 procent", 2026).\n- Gränsdragning under sänkningen: servering på plats är en restaurangtjänst med 12 procent moms, medan hämtmat utan serveringstjänster räknas som livsmedel med 6 procent moms.',
    source: "Skatteverket — Avdragsrätt för ingående moms; Mervärdesskattelagen (2023:200)",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-19",
  },
  {
    id: "moms-avdrag-grunder#2",
    docId: "moms-avdrag-grunder",
    title: "Momsavdrag — grunderna för ingående moms",
    heading: "Vanliga avdragsförbud och begränsningar",
    text: "- Stadigvarande bostad: inget momsavdrag, även om bostaden delvis används i verksamheten.\n- Personbilar: inget avdrag för moms vid inköp (med undantag för vissa branscher); 50 procent avdrag på leasingavgift när bilen används i mer än ringa omfattning i momspliktig verksamhet.\n- Representation: momsavdrag medges på ett underlag om högst 300 kronor exklusive moms per person och tillfälle för måltider och enklare förtäring.\n- Uttag och privat användning kan utlösa uttagsbeskattning i stället för att begränsa avdraget.",
    source: "Skatteverket — Avdragsrätt för ingående moms; Mervärdesskattelagen (2023:200)",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-19",
  },
  {
    id: "moms-avdrag-grunder#3",
    docId: "moms-avdrag-grunder",
    title: "Momsavdrag — grunderna för ingående moms",
    heading: "Redovisning i momsdeklarationen",
    text: "- Utgående moms redovisas i rutorna 10–12 (per skattesats), momspliktig försäljning i ruta 05.\n- Ingående moms redovisas i ruta 48.\n- Ruta 49 visar nettot: moms att betala (positivt) eller moms att få tillbaka (negativt).\n- Momsen redovisas i den period då fakturan bokförts enligt god redovisningssed (faktureringsmetoden) eller när betalning sker (bokslutsmetoden, tillåten vid omsättning högst 3 miljoner kronor).",
    source: "Skatteverket — Avdragsrätt för ingående moms; Mervärdesskattelagen (2023:200)",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-19",
  },
  {
    id: "moms-avdrag-grunder#4",
    docId: "moms-avdrag-grunder",
    title: "Momsavdrag — grunderna för ingående moms",
    heading: "Dokumentation",
    text: "- Underlaget (fakturan) är räkenskapsinformation och ska arkiveras enligt bokföringslagen i 7 år efter utgången av det kalenderår då räkenskapsåret avslutades.",
    source: "Skatteverket — Avdragsrätt för ingående moms; Mervärdesskattelagen (2023:200)",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-19",
  },
  {
    id: "moms-deklarationstider#0",
    docId: "moms-deklarationstider",
    title: "Momsdeklaration — redovisningsperioder och deklarationstidpunkter",
    heading: "Redovisningsperioder",
    text: "- Momsen redovisas per kalendermånad, kalenderkvartal eller beskattningsår (26 kap. skatteförfarandelagen (2011:1244)).\n- Kvartalsredovisning får väljas när beskattningsunderlaget är högst 40 miljoner kronor per beskattningsår.\n- Helårsredovisning (beskattningsår) får väljas när beskattningsunderlaget är högst 1 miljon kronor.\n- Byte av redovisningsperiod anmäls till Skatteverket och gäller normalt framåt i tiden.",
    source: "Skatteverket — Deklarationstidpunkter för moms; skatteförfarandelagen 26 kap.",
    url: "https://www.skatteverket.se/foretag/moms/deklareraochbetalamoms",
    effective: "2026-07-04",
  },
  {
    id: "moms-deklarationstider#1",
    docId: "moms-deklarationstider",
    title: "Momsdeklaration — redovisningsperioder och deklarationstidpunkter",
    heading: "Månads- och kvartalsmoms vid omsättning högst 40 miljoner kronor",
    text: "- Deklaration och betalning ska vara hos Skatteverket senast den 12:e i andra månaden efter redovisningsperiodens utgång.\n- Undantag: i januari och augusti är tidpunkten i stället den 17:e.\n- Exempel, kvartalsmoms: januari–mars → 12 maj; april–juni → 17 augusti; juli–september → 12 november; oktober–december → 12 februari året därpå.\n- Exempel, månadsmoms: maj → 12 juli; juni → 17 augusti; november → 17 januari (tidpunkten infaller i januari och flyttas därför från den 12:e till den 17:e).",
    source: "Skatteverket — Deklarationstidpunkter för moms; skatteförfarandelagen 26 kap.",
    url: "https://www.skatteverket.se/foretag/moms/deklareraochbetalamoms",
    effective: "2026-07-04",
  },
  {
    id: "moms-deklarationstider#2",
    docId: "moms-deklarationstider",
    title: "Momsdeklaration — redovisningsperioder och deklarationstidpunkter",
    heading: "Helårsmoms (redovisningsperiod ett beskattningsår)",
    text: "- Utan EU-handel: deklarationen ska vara inne senast den 26:e i andra månaden efter beskattningsårets utgång; när tidpunkten infaller i december gäller i stället den 27:e.\n- Räkenskapsår som slutar den 31 december → deklaration och betalning senast den 26 februari året därpå.\n- Räkenskapsår som slutar den 31 oktober → deklaration senast den 27 december samma år.\n- Företag som bedriver EU-handel har en tidigare deklarationstidpunkt än företag utan EU-handel.",
    source: "Skatteverket — Deklarationstidpunkter för moms; skatteförfarandelagen 26 kap.",
    url: "https://www.skatteverket.se/foretag/moms/deklareraochbetalamoms",
    effective: "2026-07-04",
  },
  {
    id: "moms-deklarationstider#3",
    docId: "moms-deklarationstider",
    title: "Momsdeklaration — redovisningsperioder och deklarationstidpunkter",
    heading: "Större företag (beskattningsunderlag över 40 miljoner kronor)",
    text: "- Månadsredovisning är obligatorisk.\n- Deklaration och betalning senast den 26:e i månaden efter redovisningsperiodens utgång; i december gäller den 27:e.",
    source: "Skatteverket — Deklarationstidpunkter för moms; skatteförfarandelagen 26 kap.",
    url: "https://www.skatteverket.se/foretag/moms/deklareraochbetalamoms",
    effective: "2026-07-04",
  },
  {
    id: "moms-deklarationstider#4",
    docId: "moms-deklarationstider",
    title: "Momsdeklaration — redovisningsperioder och deklarationstidpunkter",
    heading: "Helgförskjutning",
    text: "- Om deklarations- eller betalningsdagen infaller på en lördag, söndag eller allmän helgdag flyttas tidpunkten till närmast följande vardag.\n- Betalningen ska vara bokförd på Skatteverkets konto senast på förfallodagen — det räcker inte att den är skickad.",
    source: "Skatteverket — Deklarationstidpunkter för moms; skatteförfarandelagen 26 kap.",
    url: "https://www.skatteverket.se/foretag/moms/deklareraochbetalamoms",
    effective: "2026-07-04",
  },
  {
    id: "personbil-moms#0",
    docId: "personbil-moms",
    title: "Personbilar — momsregler vid köp, leasing och drift",
    heading: "Inköp av personbil",
    text: "- Huvudregel: ingen avdragsrätt för ingående moms vid inköp av en personbil, även om bilen används i den momspliktiga verksamheten.\n- Undantag — fullt avdrag medges när bilen köps för: återförsäljning (bilhandel), uthyrning, taxitrafik, körkortsutbildning (trafikskola) eller transport av avlidna.\n- Den moms som inte får dras av räknas i stället in i bilens anskaffningsvärde.",
    source: "Skatteverket — Moms på personbilar och motorcyklar",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-04",
  },
  {
    id: "personbil-moms#1",
    docId: "personbil-moms",
    title: "Personbilar — momsregler vid köp, leasing och drift",
    heading: "Vad som räknas som personbil i momshänseende",
    text: "- Personbil enligt vägtrafikregistret, samt vissa andra fordon: en lätt lastbil med skåpkarosseri utan separat förarhytt räknas som personbil i momshänseende.\n- Lätta lastbilar med flak eller med separat förarhytt räknas däremot inte som personbil — där gäller de allmänna avdragsreglerna.\n- Motorcyklar behandlas i dessa regler på samma sätt som personbilar.",
    source: "Skatteverket — Moms på personbilar och motorcyklar",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-04",
  },
  {
    id: "personbil-moms#2",
    docId: "personbil-moms",
    title: "Personbilar — momsregler vid köp, leasing och drift",
    heading: "Leasing och hyra",
    text: "- Vid leasing eller långtidshyra av personbil får 50 procent av momsen på leasing-/hyresavgiften dras av, om bilen används i mer än ringa omfattning i den momspliktiga verksamheten.\n- Med mer än ringa omfattning avses enligt Skatteverkets praxis körning om minst 100 mil per år i verksamheten.\n- Halva avdraget gäller schablonmässigt oavsett den faktiska fördelningen mellan körning i verksamheten och privat körning.\n- Om bilen uteslutande används för de undantagna ändamålen (till exempel taxitrafik) medges fullt avdrag även på leasingavgiften.",
    source: "Skatteverket — Moms på personbilar och motorcyklar",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-04",
  },
  {
    id: "personbil-moms#3",
    docId: "personbil-moms",
    title: "Personbilar — momsregler vid köp, leasing och drift",
    heading: "Driftskostnader",
    text: "- Full avdragsrätt gäller för moms på driftskostnader — drivmedel, service, reparationer, besiktning och liknande — om bilen är en tillgång i verksamheten eller har hyrts för användning i den.\n- Det fulla driftsavdraget gäller även när bilen delvis används privat.",
    source: "Skatteverket — Moms på personbilar och motorcyklar",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-04",
  },
  {
    id: "personbil-moms#4",
    docId: "personbil-moms",
    title: "Personbilar — momsregler vid köp, leasing och drift",
    heading: "Bokföring",
    text: "- Personbilskostnader bokförs i kontogrupp 56, till exempel 5610 Personbilskostnader, 5611 Drivmedel för personbilar och 5615 Leasing av personbilar.\n- Ej avdragsgill moms på leasingavgiften (den 50-procentiga delen) ingår i leasingkostnaden.",
    source: "Skatteverket — Moms på personbilar och motorcyklar",
    url: "https://www.skatteverket.se/foretag/moms",
    effective: "2026-07-04",
  },
  {
    id: "representation#0",
    docId: "representation",
    title: "Representation — avdrag och moms",
    heading: "Inkomstskatt: måltider är inte avdragsgilla",
    text: "- Sedan den 1 januari 2017 är utgifter för lunch, middag, supé och annan förtäring vid representation inte avdragsgilla vid inkomstbeskattningen (16 kap. 2 § inkomstskattelagen).\n- Undantag: enklare förtäring av mindre värde som inte ersätter en måltid — till exempel kaffe, te, kakor, frukt eller en enklare smörgås — är avdragsgill upp till 60 kronor exklusive moms per person och tillfälle.\n- Kringkostnader vid representation, till exempel lokalhyra eller teaterbiljetter, är avdragsgilla upp till 180 kronor exklusive moms per person och tillfälle.\n- Representationen ska ha ett omedelbart samband med verksamheten, till exempel affärsförhandlingar eller personalvård, och får inte vara av personlig karaktär.",
    source: "Skatteverket — Representation; inkomstskattelagen 16 kap. 2 §",
    url: "https://www.skatteverket.se/foretag/skatterochavdrag/avdragforforetag/representation",
    effective: "2026-07-19",
  },
  {
    id: "representation#1",
    docId: "representation",
    title: "Representation — avdrag och moms",
    heading: "Moms: avdrag på underlag upp till 300 kronor",
    text: "- Momsavdrag medges på ett underlag om högst 300 kronor exklusive moms per person och tillfälle för mat och dryck vid representation.\n- Vid 25 procent moms är det maximala avdraget 75 kronor per person; vid 12 procent moms (till exempel servering på restaurang) 36 kronor per person; vid 6 procent moms (livsmedel och hämtmat under den tillfälliga sänkningen 1 april 2026–31 december 2027) 18 kronor per person.\n- När både mat och alkohol (25 procent) ingår får avdraget i stället beräknas med schablon, förutsatt att kostnaden överstiger 300 kronor exklusive moms per person och att den debiterade momsen är minst schablonbeloppet: 46 kronor per person och tillfälle när maten har 12 procent moms, respektive 33 kronor per person och tillfälle när maten har 6 procent moms (Skatteverket — Avdrag för moms vid representation).\n- Överskjutande moms — den del som avser underlag över 300 kronor — får varken dras av som moms eller som kostnad utöver de vanliga representationsreglerna.",
    source: "Skatteverket — Representation; inkomstskattelagen 16 kap. 2 §",
    url: "https://www.skatteverket.se/foretag/skatterochavdrag/avdragforforetag/representation",
    effective: "2026-07-19",
  },
  {
    id: "representation#2",
    docId: "representation",
    title: "Representation — avdrag och moms",
    heading: "Kontering",
    text: "- 6071 Representation, avdragsgill — används för den avdragsgilla delen (enklare förtäring inom 60 kronor, kringkostnader inom 180 kronor).\n- 6072 Representation, ej avdragsgill — används för måltidskostnader och belopp över gränserna.\n- Den avdragsgilla momsen (inom 300-kronorsunderlaget) bokförs som vanligt på 2640 Ingående moms; resterande moms ingår i kostnaden på 6072.",
    source: "Skatteverket — Representation; inkomstskattelagen 16 kap. 2 §",
    url: "https://www.skatteverket.se/foretag/skatterochavdrag/avdragforforetag/representation",
    effective: "2026-07-19",
  },
  {
    id: "representation#3",
    docId: "representation",
    title: "Representation — avdrag och moms",
    heading: "Intern och extern representation",
    text: "- Samma beloppsgränser för momsavdrag gäller för extern representation (kunder, leverantörer) och intern representation (personal).\n- För intern representation gäller enligt Skatteverkets allmänna råd att högst två personalfester per år bör vara underlag för avdrag för kringkostnader.\n- Vid demonstrationer och visningar kan enklare förtäring upp till 60 kronor vara avdragsgill enligt samma mönster.",
    source: "Skatteverket — Representation; inkomstskattelagen 16 kap. 2 §",
    url: "https://www.skatteverket.se/foretag/skatterochavdrag/avdragforforetag/representation",
    effective: "2026-07-19",
  },
  {
    id: "sie-format#0",
    docId: "sie-format",
    title: "SIE-formatet — export och import av redovisningsdata",
    heading: "Vad SIE är",
    text: "- SIE är ett svenskt standardformat för att utbyta redovisningsdata mellan program, till exempel mellan försystem, bokföringsprogram, bokslutsprogram och revisorer.\n- Formatet förvaltas av Föreningen SIE-gruppen.\n- Typerna: SIE 1 (årssaldon), SIE 2 (periodsaldon), SIE 3 (objektsaldon) och SIE 4 (transaktioner — kompletta verifikationer).\n- SIE 4 finns i två varianter: 4E (export från bokföringsprogram, med saldon och verifikationer) och 4I (import av verifikationer till bokföringsprogram).\n- Vanliga filändelser är .se för typ 4E och .si för typ 4I.",
    source: "Föreningen SIE-gruppen — SIE-formatets tekniska beskrivning",
    url: "https://sie.se/",
    effective: "2026-07-04",
  },
  {
    id: "sie-format#1",
    docId: "sie-format",
    title: "SIE-formatet — export och import av redovisningsdata",
    heading: "Teknisk uppbyggnad",
    text: "- En SIE-fil är en textfil där varje rad inleds med en etikett med #-prefix.\n- Teckenkodningen enligt standarden är IBM PC 8-bitars teckentabell (Code page 437) — etiketten #FORMAT anger värdet PC8.\n- Obligatoriska identifikationsposter: #FLAGGA, #PROGRAM, #FORMAT, #GEN (genereringsdatum), #SIETYP och #FNAMN (företagsnamn).\n- Vanliga metadataposter: #ORGNR (organisationsnummer), #RAR (räkenskapsår), #KONTO (kontonummer och kontonamn), #SRU (SRU-kod per konto), #IB och #UB (ingående och utgående balans per konto) samt #RES (resultat per konto).\n- Datum skrivs i formatet ÅÅÅÅMMDD.",
    source: "Föreningen SIE-gruppen — SIE-formatets tekniska beskrivning",
    url: "https://sie.se/",
    effective: "2026-07-04",
  },
  {
    id: "sie-format#2",
    docId: "sie-format",
    title: "SIE-formatet — export och import av redovisningsdata",
    heading: "Verifikationer i SIE 4",
    text: "- En verifikation inleds med posten #VER med fälten serie, verifikationsnummer, verifikationsdatum och verifikationstext.\n- Verifikationens transaktionsrader anges med #TRANS inom klamrar { } och innehåller kontonummer, objektlista, belopp samt valfritt transaktionsdatum, transaktionstext och kvantitet.\n- Debet anges som positivt belopp och kredit som negativt belopp.\n- Transaktionsraderna i en verifikation ska summera till noll — filen bär själv sin balanskontroll.\n- Posterna #RTRANS och #BTRANS kan förekomma för att beskriva rättade respektive borttagna transaktionsrader.",
    source: "Föreningen SIE-gruppen — SIE-formatets tekniska beskrivning",
    url: "https://sie.se/",
    effective: "2026-07-04",
  },
  {
    id: "sie-format#3",
    docId: "sie-format",
    title: "SIE-formatet — export och import av redovisningsdata",
    heading: "Användning i praktiken",
    text: "- SIE 4I används för att föra in verifikationer från försystem (till exempel fakturering eller lönesystem) i bokföringen.\n- SIE 4E används för att lämna hela bokföringen vidare, till exempel till revisor, bokslutsprogram eller vid byte av bokföringsprogram.\n- Kontoplanen i filen (posterna #KONTO) följer i praktiken BAS-kontoplanens fyrsiffriga kontonummer.",
    source: "Föreningen SIE-gruppen — SIE-formatets tekniska beskrivning",
    url: "https://sie.se/",
    effective: "2026-07-04",
  },
];
